version: '3'
services:
  yioj-backend-user-service:
    container_name: yioj-backend-user-service
    build:
      context: ./yioj-backend-user-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - yinetwork
    depends_on:
      - yioj-backend-gateway

  yioj-backend-submission-service:
    container_name: yioj-backend-submission-service
    build:
      context: ./yioj-backend-submission-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - yinetwork
    depends_on:
      - yioj-backend-gateway
      - yioj-backend-user-service
      - yioj-backend-problem-service

  yioj-backend-problem-service:
    container_name: yioj-backend-problem-service
    build:
      context: ./yioj-backend-problem-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    networks:
      - yinetwork
    depends_on:
      - yioj-backend-gateway
      - yioj-backend-user-service

  yioj-backend-comment-service:
    container_name: yioj-backend-comment-service
    build:
      context: ./yioj-backend-comment-service
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    networks:
      - yinetwork
    depends_on:
      - yioj-backend-user-service
      - yioj-backend-gateway

  yioj-backend-gateway:
    container_name: yioj-backend-gateway
    build:
      context: ./yioj-backend-gateway
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    networks:
      - yinetwork
networks:
  yinetwork: