version: '3'
services:
  mysql:
    image: mysql:8
    container_name: yioj-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - yinetwork
  redis:
    image: redis:7.0
    container_name: yioj-redis
    ports:
      - "6379:6379"
    networks:
      - yinetwork
    volumes:
      - ./.redis-data:/data
  rabbitmq:
    restart: always
    hostname: rabbitmq
    image: rabbitmq:3.12.6-management
    container_name: yioj-rabbitmq
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    # volumes:
    #   - ./.rabbitmq-data:/var/lib/rabbitmq
    volumes:
      - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - yinetwork
    privileged: true
  nacos:
    restart: always
    image: nacos/nacos-server:v2.2.0
    container_name: yioj-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      -  ./.nacos-data:/home/nacos/data
    networks:
      - yinetwork
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - TZ=Asia/Shanghai
  # elasticsearch:
  #   image: elasticsearch:7.14.1
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-cluster-ai66
  #     - cluster.initial_master_nodes=es01
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - /.elasticsearch-data/docker-compose/elastic/es01/data:/usr/share/elasticsearch/data
  #     - /.elasticsearch-data/docker-compose/elastic/es01/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - yinetwork
networks:
  yinetwork: