# 公共配置文件
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  application:
    name: yioj-backend-submission-service
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/yi_oj
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
    password:
    lettuce:
      pool:
        max-idle: 16
        max-active: 16
        min-idle: 8
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8003
  servlet:
    context-path: /api/submission
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
resilience4j:
  ratelimiter:
    instances:
      submissionRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5000ms
  circuitbreaker:
    instances:
      submissionCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permitted-number-of-calls-in-half-open-state: 3
        waitDurationInOpenState: 5000
        failure-rate-threshold: 50
sandbox:
  type: example
  remote-url: http://127.0.0.1:8103/codeSandbox/runProblem
knife4j:
  enable: true